defaults:
  - base
optimizer_backend:
  _target_: "ray_optim.ax.OptimizerBackendAx"
  ax_client:
    _target_: "ax.service.ax_client.AxClient"
    generation_strategy:
      _target_: "ax.modelbridge.generation_strategy.GenerationStrategy"
      steps:
        - _target_: "ray_optim.ax.get_step"
          model: "SOBOL"
          num_trials: 5
          max_parallelism: 3