_target_: "ray_optim.ray_optimizer.RayOptimizer"
criterion:
  _target_: "sub_projects.ray_optimization.losses.geometric.SinkhornLoss"
exported_plane: ${optimization_target_configuration.exported_plane}
engine: ${optimization_target_configuration.engine}
log_times: True
plot_interval: 10
iterations: 1000
transforms: ${optimization_target_configuration.transforms}
logging_backend: ${logging_backend}