_target_: "ray_optim.ray_optimizer.RayOptimizer"
criterion:
  _target_: "sub_projects.ray_optimization.losses.geometric.SinkhornLoss"
exported_plane: ${target_configuration.exported_plane}
engine: ${target_configuration.engine}
secondary_engine: ${target_configuration.secondary_engine}
log_times: True
plot_interval: 10
iterations: 1000
transforms: ${target_configuration.transforms}
logging_backend: ${logging_backend}