defaults:
  - base
optimizer_backend:
  _target_: "ray_optim.ray_optimizer.OptimizerBackendBasinhopping"
  basinhopping_function:
    _target_: hydra.utils.get_method
    path: "scipy.optimize.basinhopping"