defaults:
  - base
optimizer_backend:
  _target_: "ray_optim.ray_optimizer.OptimizerBackendOptuna"
  optuna_study:
    _target_: "optuna.create_study"
    sampler:
      _target_: "optuna.samplers.TPESampler"
    pruner:
      _target_: "optuna.pruners.HyperbandPruner"
    storage: "sqlite:////dev/shm/db.sqlite2"
    study_name: ${study_name}
    load_if_exists: True