defaults:
  - base
optimizer_backend:
  _target_: "ray_optim.optuna.OptimizerBackendOptuna"
  optuna_study:
    _target_: "optuna.create_study"
    sampler:
      _target_: "optuna.samplers.TPESampler"
    pruner:
      _target_: "optuna.pruners.HyperbandPruner"
    load_if_exists: False