_target_: "sub_projects.ray_optimization.ray_optimization.TargetConfiguration"
param_func:
    _target_: "sub_projects.ray_optimization.configuration.params_to_func"
    _convert_: "all"
    rg: ${rg}
    parameters:
      number_rays: 1e3
      x_dir: 0.
      y_dir: 0.
      z_dir: 1.
      direction_spread: 0.
      correlation_factor: [-1.0, 1.0]
      x_mean: [-2., 2.]
      y_mean: [-2., 2.]
      x_var: [0.001, 0.01]
      y_var: [0.001, 0.01]
    enforce_lims_keys:
      - "x_var"
      - "y_var"
      - "correlation_factor"
engine:
  _target_: "ray_tools.base.engine.GaussEngine"
  device:
    _target_: "torch.device"
    device: "cpu"
num_beamline_samples: 22
exported_plane: "ImagePlane"
max_sample_generation_deviation: 1.0
max_target_deviation: 0.3
max_offset_search_deviation: 0.3
transforms:
  _target_: "ray_tools.base.transform.MultiLayer"
  dist_layers: [0., 1., 2.]
logging_project: "gauss"
