defaults:
  - metrixs
real_data_configuration:
  _target_: "sub_projects.ray_optimization.configuration.RealDataConfiguration"
  path: 'datasets/metrix_real_data/2021_march_complete'
  train_set: ['M03', 'M10', 'M18', 'M22', 'M23', 'M24', 'M25', 'M27', 'M28', 'M29', 'M30', 'M32', 'M33', 'M36',
                         'M37', 'M40', 'M41', 'M42', 'M43', 'M44']
  validation_set: ['M04', 'M05', 'M06', 'M07', 'M08', 'M09', 'M11', 'M12', 'M13', 'M14', 'M15', 'M16', 'M17',
                              'M18', 'M19', 'M20', 'M21', 'M26', 'M31', 'M34', 'M35', 'M38', 'M39']
logging_project: "metrix_real"
