_target_: "sub_projects.ray_optimization.ray_optimization.TargetConfiguration"
param_func:
    _target_: "sub_projects.ray_optimization.configuration.params_to_func"
    _convert_: "all"
    rg: ${rg}
    parameters:
      U41_318eV.numberRays: 10000.0
      U41_318eV.translationXerror: [-0.25, 0.25]
      U41_318eV.translationYerror: [-0.25, 0.25]
      U41_318eV.rotationXerror: [-0.05, 0.05]
      U41_318eV.rotationYerror: [-0.05, 0.05]
      ASBL.totalWidth: [1.9, 2.1]
      ASBL.totalHeight: [0.9, 1.1]
      ASBL.translationXerror: [-0.2, 0.2]
      ASBL.translationYerror: [-0.2, 0.2]
      M1_Cylinder.radius: [174.06, 174.36]
      M1_Cylinder.rotationXerror: [-0.25, 0.25]
      M1_Cylinder.rotationYerror: [-1.0, 1.0]
      M1_Cylinder.rotationZerror: [-1.0, 1.0]
      M1_Cylinder.translationXerror: [-1.0, 1.0]
      M1_Cylinder.translationYerror: [-1.0, 1.0]
      SphericalGrating.radius: [109741.0, 109841.0]
      SphericalGrating.rotationYerror: [-1.0, 1.0]
      SphericalGrating.rotationZerror: [-2.5, 2.5]
      ExitSlit.totalHeight: [0.009, 0.011]
      ExitSlit.translationZerror: [-150.0, 150.0]
      ExitSlit.rotationZerror: [-0.3, 0.3]
      E1.longHalfAxisA: [20600.0, 20900.0]
      E1.shortHalfAxisB: [300.721702601, 304.721702601]
      E1.rotationXerror: [-1.5, 1.5]
      E1.rotationYerror: [-7.5, 7.5]
      E1.rotationZerror: [7, 14]
      E1.translationYerror: [-1, 1]
      E1.translationZerror: [-1, 1]
      E2.longHalfAxisA: [4325.0, 4425.0]
      E2.shortHalfAxisB: [96.1560870104, 98.1560870104]
      E2.rotationXerror: [-0.5, 0.5]
      E2.rotationYerror: [-7.5, 7.5]
      E2.rotationZerror: [22.0, 32.0]
      E2.translationYerror: [-1, 1]
      E2.translationZerror: [-1, 1]
      ImagePlane.translationXerror: [-3.33, 3.33]
      ImagePlane.translationYerror: [-3.33, 3.33]
      ImagePlane.translationZerror: [-3.33, 3.33]
    output_parameters:
      - "ImagePlane.translationXerror"
      - "ImagePlane.translationYerror"
      - "ImagePlane.translationZerror"
engine:
  _target_: "ray_tools.base.engine.RayEngine"
  rml_basefile: "rml_src/METRIX_U41_G1_H1_318eV_PS_MLearn.rml"
  exported_planes:
    - ${target_configuration.exported_plane}
  ray_backend:
    _target_: 'ray_tools.base.backend.RayBackendDockerRAYUI'
    docker_image: 'ray-ui-service'
    dockerfile_path: 'ray_docker/rayui'
    ray_workdir:
      _target_: 'sub_projects.ray_optimization.configuration.build_ray_workdir_path'
      parent_path: '/dev/shm/ray_workdir'
    verbose: False
  num_workers: -1
num_beamline_samples: 22
exported_plane: "ImagePlane"
max_sample_generation_deviation: 0.001
max_target_deviation: 0.3
max_offset_search_deviation: 0.3
z_layers: [-15, -10, -5, 0, 5, 10, 15, 20, 25, 30]
transforms:
  _target_: "ray_tools.base.transform.MultiLayer"
  dist_layers: ${target_configuration.z_layers}
  copy_directions: False
logging_project: "metrix"
